from __future__ import annotations

from typing import TypedDict


class EntitySchema(TypedDict):
    collection: str
    required: list[str]
    optional: list[str]


ENTITY_SCHEMAS: dict[str, EntitySchema] = {
    "workspace": {
        "collection": "workspaces",
        "required": [
            "id",
            "name",
            "category",
            "address",
            "country",
            "timezone",
            "locale",
            "plan",
            "billingCycle",
            "status",
            "subscriptionStatus",
            "trialEndsAt",
            "planStartedAt",
            "ownerUserId",
            "createdAt",
            "updatedAt",
        ],
        "optional": ["deletedAt"],
    },
    "business": {
        "collection": "businesses",
        "required": ["id", "workspaceId", "name", "category", "address", "phone", "email", "taxId", "currency", "isPrimary", "createdAt", "updatedAt"],
        "optional": [],
    },
    "workspaceRole": {
        "collection": "roles",
        "required": ["id", "workspaceId", "name", "slug", "description", "systemRole", "permissions", "createdBy", "createdAt", "updatedAt"],
        "optional": [],
    },
    "user": {
        "collection": "users",
        "required": [
            "id",
            "workspaceId",
            "roleId",
            "name",
            "email",
            "emailNormalized",
            "role",
            "status",
            "lastActive",
            "phone",
            "avatarUrl",
            "locale",
            "isEmailVerified",
            "invitedBy",
            "lastLoginAt",
            "passwordSalt",
            "passwordHash",
            "createdAt",
            "updatedAt",
        ],
        "optional": [],
    },
    "session": {
        "collection": "sessions",
        "required": ["accessTokenHash", "refreshTokenHash", "userId", "expiresAt", "refreshExpiresAt", "userAgent", "ipAddress", "createdAt"],
        "optional": ["revokedAt"],
    },
    "passwordResetToken": {
        "collection": "password_reset_tokens",
        "required": ["id", "userId", "tokenHash", "requestedIp", "expiresAt", "createdAt"],
        "optional": ["usedAt"],
    },
    "workspaceSettings": {
        "collection": "settings",
        "required": [
            "workspaceId",
            "businessName",
            "panVatNumber",
            "currency",
            "language",
            "timezone",
            "fiscalYearStart",
            "dateFormat",
            "numberFormat",
            "taxRate",
            "invoicePrefix",
            "receiptFooter",
            "defaultPaymentMethod",
            "compactTables",
            "lowStockAlerts",
            "dailySalesSummary",
            "newCustomerSignup",
            "twoFactorEnabled",
            "scheduledReports",
        ],
        "optional": [],
    },
    "recordEnvelope": {
        "collection": "records",
        "required": ["workspaceId", "kind", "id", "payload", "createdAt", "updatedAt"],
        "optional": ["deletedAt"],
    },
    "platformAdmin": {
        "collection": "platform_admins",
        "required": [
            "id",
            "name",
            "email",
            "emailNormalized",
            "role",
            "status",
            "lastActive",
            "phone",
            "permissions",
            "lastLoginAt",
            "passwordSalt",
            "passwordHash",
            "createdBy",
            "createdAt",
            "updatedAt",
        ],
        "optional": [],
    },
    "platformSession": {
        "collection": "platform_sessions",
        "required": ["accessTokenHash", "adminId", "expiresAt", "userAgent", "ipAddress", "createdAt"],
        "optional": ["revokedAt"],
    },
    "platformFeatureFlag": {
        "collection": "platform_feature_flags",
        "required": ["id", "name", "description", "area", "enabled", "rollout", "risk", "createdAt", "updatedAt"],
        "optional": [],
    },
    "sale": {
        "collection": "records",
        "required": [
            "id",
            "invoiceNo",
            "businessId",
            "customerId",
            "customer",
            "products",
            "items",
            "subtotal",
            "discountTotal",
            "taxTotal",
            "amount",
            "currency",
            "payment",
            "status",
            "date",
            "notes",
            "createdBy",
            "createdAt",
            "updatedAt",
            "auditTrail",
        ],
        "optional": ["deletedAt"],
    },
    "saleLineItem": {
        "collection": "records",
        "required": ["productId", "productName", "sku", "quantity", "unitPrice", "costPrice", "discount", "tax", "lineTotal"],
        "optional": [],
    },
    "customer": {
        "collection": "records",
        "required": [
            "id",
            "name",
            "company",
            "email",
            "phone",
            "address",
            "source",
            "taxId",
            "notes",
            "tags",
            "creditLimit",
            "balance",
            "totalSpent",
            "orders",
            "lastOrder",
            "segment",
            "birthday",
            "preferredLanguage",
            "createdAt",
            "updatedAt",
        ],
        "optional": [],
    },
    "supplier": {
        "collection": "records",
        "required": ["id", "name", "phone", "email", "address", "pan", "contactPerson", "payableBalance", "notes", "createdAt", "updatedAt"],
        "optional": [],
    },
    "creditLedgerEntry": {
        "collection": "records",
        "required": ["id", "customerId", "customerName", "type", "amount", "date", "note", "createdBy", "createdAt"],
        "optional": ["saleId", "invoiceNo", "dueDate", "paymentMethod"],
    },
    "party": {
        "collection": "records",
        "required": ["id", "name", "type", "phone", "email", "address", "pan", "openingBalance", "creditLimit", "dueDays", "notes", "balance", "createdAt", "updatedAt"],
        "optional": [],
    },
    "partyLedgerEntry": {
        "collection": "records",
        "required": ["id", "partyId", "partyName", "direction", "type", "amount", "date", "note", "createdBy", "createdAt"],
        "optional": ["dueDate", "referenceId"],
    },
    "purchase": {
        "collection": "records",
        "required": ["id", "supplierId", "supplierName", "billNo", "date", "dueDate", "items", "subtotal", "discountTotal", "taxTotal", "amount", "payment", "status", "notes", "attachmentIds", "createdBy", "createdAt", "updatedAt"],
        "optional": [],
    },
    "expense": {
        "collection": "records",
        "required": ["id", "category", "vendor", "amount", "taxAmount", "paymentAccountId", "paymentMethod", "date", "recurring", "note", "attachmentIds", "createdBy", "createdAt", "updatedAt"],
        "optional": [],
    },
    "cashBankAccount": {
        "collection": "records",
        "required": ["id", "name", "type", "institution", "accountNumber", "openingBalance", "balance", "active", "createdAt", "updatedAt"],
        "optional": [],
    },
    "moneyMovement": {
        "collection": "records",
        "required": ["id", "accountId", "accountName", "type", "amount", "date", "note", "createdBy", "createdAt"],
        "optional": ["partyId", "partyName", "referenceId"],
    },
    "journalEntry": {
        "collection": "records",
        "required": ["id", "date", "source", "sourceId", "memo", "lines", "locked", "createdBy", "createdAt"],
        "optional": [],
    },
    "documentAttachment": {
        "collection": "records",
        "required": ["id", "name", "recordType", "recordId", "fileName", "mimeType", "size", "uploadedBy", "createdAt"],
        "optional": ["dataUrl"],
    },
    "billScan": {
        "collection": "records",
        "required": [
            "id",
            "sourceType",
            "status",
            "fileName",
            "mimeType",
            "size",
            "imageDataUrl",
            "rawText",
            "parsed",
            "approved",
            "confidence",
            "targetRecordType",
            "targetRecordId",
            "pdfDocumentId",
            "createdBy",
            "createdAt",
            "updatedAt",
        ],
        "optional": [],
    },
    "reminderTemplate": {
        "collection": "records",
        "required": ["id", "name", "channel", "language", "message", "daysOffset", "active"],
        "optional": [],
    },
    "reminderLog": {
        "collection": "records",
        "required": ["id", "partyId", "partyName", "channel", "message", "amount", "dueDate", "status", "createdBy", "createdAt"],
        "optional": [],
    },
    "syncOperation": {
        "collection": "records",
        "required": ["id", "operationKey", "entity", "entityId", "action", "payload", "status", "createdAt"],
        "optional": ["error", "syncedAt"],
    },
    "inventoryProduct": {
        "collection": "records",
        "required": [
            "id",
            "name",
            "description",
            "sku",
            "barcode",
            "brand",
            "category",
            "unit",
            "stock",
            "reorderLevel",
            "price",
            "costPrice",
            "taxRate",
            "supplier",
            "location",
            "status",
            "active",
            "createdAt",
            "updatedAt",
        ],
        "optional": [],
    },
    "inventoryMovement": {
        "collection": "records",
        "required": ["id", "businessId", "productId", "productName", "delta", "stockBefore", "stockAfter", "reason", "referenceId", "note", "user", "createdAt"],
        "optional": [],
    },
    "inventoryCategory": {
        "collection": "records",
        "required": ["id", "name", "createdBy", "createdAt", "updatedAt"],
        "optional": [],
    },
    "expenseCategory": {
        "collection": "records",
        "required": ["id", "name", "createdBy", "createdAt", "updatedAt"],
        "optional": [],
    },
    "generatedReport": {
        "collection": "records",
        "required": ["id", "title", "type", "template", "range", "status", "format", "createdBy", "downloadUrl", "scheduledAt", "createdAt"],
        "optional": [],
    },
    "auditLog": {
        "collection": "records",
        "required": ["id", "actorId", "user", "action", "module", "detail", "ipAddress", "metadata", "createdAt"],
        "optional": [],
    },
    "billingRecord": {
        "collection": "records",
        "required": ["id", "description", "gateway", "plan", "billingCycle", "amount", "currency", "invoiceNo", "date", "paidAt", "status"],
        "optional": [],
    },
    "featureFlag": {
        "collection": "records",
        "required": ["id", "name", "description", "area", "enabled", "rollout", "risk", "createdAt", "updatedAt"],
        "optional": [],
    },
    "supportTicket": {
        "collection": "records",
        "required": ["id", "orgId", "orgName", "subject", "priority", "status", "assignedTo", "channel", "createdAt", "lastUpdatedAt"],
        "optional": [],
    },
}

RECORD_SCHEMA_BY_KIND = {
    "sales": "sale",
    "parties": "party",
    "party_ledger": "partyLedgerEntry",
    "purchases": "purchase",
    "expenses": "expense",
    "expense_categories": "expenseCategory",
    "cash_bank_accounts": "cashBankAccount",
    "money_movements": "moneyMovement",
    "journal_entries": "journalEntry",
    "documents": "documentAttachment",
    "bill_scans": "billScan",
    "reminder_templates": "reminderTemplate",
    "reminder_logs": "reminderLog",
    "sync_operations": "syncOperation",
    "customers": "customer",
    "suppliers": "supplier",
    "credit_ledger": "creditLedgerEntry",
    "inventory": "inventoryProduct",
    "inventory_categories": "inventoryCategory",
    "inventory_movements": "inventoryMovement",
    "reports": "generatedReport",
    "audit_logs": "auditLog",
    "billing_history": "billingRecord",
    "feature_flags": "featureFlag",
    "support_tickets": "supportTicket",
}
