from __future__ import annotations

ALL_PERMISSIONS: list[str] = [
    "dashboard.view",
    "sales.view",
    "sales.create",
    "sales.update",
    "sales.delete",
    "parties.view",
    "parties.manage",
    "purchases.view",
    "purchases.manage",
    "expenses.view",
    "expenses.manage",
    "customers.view",
    "customers.manage",
    "inventory.view",
    "inventory.manage",
    "cashbank.view",
    "cashbank.manage",
    "accounting.view",
    "analytics.view",
    "reports.view",
    "reports.generate",
    "documents.view",
    "documents.manage",
    "reminders.manage",
    "sync.manage",
    "team.view",
    "users.invite",
    "users.manage",
    "roles.manage",
    "billing.manage",
    "settings.manage",
    "account.delete",
]

SYSTEM_ROLES = [
    {
        "slug": "owner",
        "name": "Owner",
        "description": "Full tenant owner access, including billing, roles, settings, and account deletion.",
        "permissions": ALL_PERMISSIONS,
    },
    {
        "slug": "manager",
        "name": "Manager",
        "description": "Operational manager access across sales, CRM, inventory, analytics, reports, and team visibility.",
        "permissions": [
            "dashboard.view",
            "sales.view",
            "sales.create",
            "sales.update",
            "parties.view",
            "parties.manage",
            "purchases.view",
            "purchases.manage",
            "expenses.view",
            "expenses.manage",
            "customers.view",
            "customers.manage",
            "inventory.view",
            "inventory.manage",
            "cashbank.view",
            "cashbank.manage",
            "accounting.view",
            "analytics.view",
            "reports.view",
            "reports.generate",
            "documents.view",
            "documents.manage",
            "reminders.manage",
            "team.view",
            "users.invite",
            "settings.manage",
        ],
    },
    {
        "slug": "staff",
        "name": "Staff",
        "description": "Frontline user with limited sales entry and stock movement permissions.",
        "permissions": [
            "dashboard.view",
            "sales.view",
            "sales.create",
            "parties.view",
            "purchases.view",
            "expenses.view",
            "customers.view",
            "inventory.view",
            "inventory.manage",
            "cashbank.view",
            "documents.view",
            "reminders.manage",
        ],
    },
    {
        "slug": "viewer",
        "name": "Viewer",
        "description": "Read-only access for dashboard, analytics, reports, and operational history.",
        "permissions": [
            "dashboard.view",
            "sales.view",
            "parties.view",
            "purchases.view",
            "expenses.view",
            "customers.view",
            "inventory.view",
            "cashbank.view",
            "accounting.view",
            "analytics.view",
            "reports.view",
            "documents.view",
        ],
    },
]

EMPTY_SETTINGS = {
    "businessName": "",
    "panVatNumber": "",
    "currency": "NPR",
    "language": "en",
    "timezone": "Asia/Kathmandu",
    "fiscalYearStart": "July",
    "dateFormat": "YYYY-MM-DD",
    "numberFormat": "en-NP",
    "taxRate": 13,
    "invoicePrefix": "RP",
    "receiptFooter": "Thank you for your business.",
    "defaultPaymentMethod": "Cash",
    "compactTables": False,
    "lowStockAlerts": True,
    "dailySalesSummary": False,
    "newCustomerSignup": False,
    "twoFactorEnabled": False,
    "scheduledReports": False,
}

PLAN_PRICES = {
    "free": 0,
    "pro_monthly": 1499,
    "pro_annual": 14990,
}

RECORD_KINDS = {
    "sales",
    "parties",
    "party_ledger",
    "purchases",
    "expenses",
    "expense_categories",
    "cash_bank_accounts",
    "money_movements",
    "journal_entries",
    "documents",
    "reminder_templates",
    "reminder_logs",
    "sync_operations",
    "customers",
    "suppliers",
    "credit_ledger",
    "inventory",
    "inventory_categories",
    "inventory_movements",
    "reports",
    "audit_logs",
    "billing_history",
    "feature_flags",
    "support_tickets",
}
