# Generated by Django 5.2.13 on 2026-05-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rp_businesses',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_normalized', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=80)),
                ('status', models.CharField(default='Active', max_length=24)),
                ('last_active', models.CharField(max_length=80)),
                ('password_salt', models.CharField(max_length=128)),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rp_users',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.CharField(blank=True, default='', max_length=240)),
                ('plan', models.CharField(default='free', max_length=20)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('status', models.CharField(default='Trial', max_length=32)),
                ('trial_ends_at', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rp_workspaces',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceRecord',
            fields=[
                ('row_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'rp_workspace_records',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('system_role', models.BooleanField(default=False)),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rp_workspace_roles',
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('access_token_hash', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='rhinopeak.useraccount')),
            ],
            options={
                'db_table': 'rp_sessions',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to='rhinopeak.useraccount')),
            ],
            options={
                'db_table': 'rp_password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='rhinopeak.workspace')),
                ('business_name', models.CharField(blank=True, default='', max_length=180)),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('fiscal_year_start', models.CharField(default='July', max_length=20)),
                ('compact_tables', models.BooleanField(default=False)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('daily_sales_summary', models.BooleanField(default=False)),
                ('new_customer_signup', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('scheduled_reports', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'rp_workspace_settings',
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['plan'], name='rp_workspac_plan_93c49e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['status'], name='rp_workspac_status_d0b3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_at'], name='rp_workspac_created_b5b319_idx'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rhinopeak.workspace'),
        ),
        migrations.AddField(
            model_name='business',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='rhinopeak.workspace'),
        ),
        migrations.AddField(
            model_name='workspacerecord',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rhinopeak.workspace'),
        ),
        migrations.AddField(
            model_name='workspacerole',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='rhinopeak.workspace'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='rhinopeak.workspacerole'),
        ),
        migrations.AddIndex(
            model_name='sessiontoken',
            index=models.Index(fields=['expires_at'], name='rp_sessions_expires_d8c312_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontoken',
            index=models.Index(fields=['revoked_at'], name='rp_sessions_revoked_18c594_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'token_hash', 'used_at'], name='rp_password_user_id_37ff65_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='rp_password_expires_b59030_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['workspace', 'created_at'], name='rp_business_workspa_242e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacerecord',
            index=models.Index(fields=['workspace', 'kind'], name='rp_workspac_workspa_d18db5_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacerecord',
            index=models.Index(fields=['workspace', 'kind', 'updated_at'], name='rp_workspac_workspa_9874eb_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacerecord',
            index=models.Index(fields=['deleted_at'], name='rp_workspac_deleted_4b91cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacerecord',
            constraint=models.UniqueConstraint(fields=('workspace', 'kind', 'id'), name='uniq_workspace_record_kind_id'),
        ),
        migrations.AddIndex(
            model_name='workspacerole',
            index=models.Index(fields=['workspace', 'system_role'], name='rp_workspac_workspa_4c53c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacerole',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_workspace_role_name'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['workspace', 'role'], name='rp_users_workspa_33ff6b_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['status'], name='rp_users_status_50e7fc_idx'),
        ),
    ]
