# Generated by Django 6.0.5 on 2026-05-18 09:13

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhinopeak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_normalized', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(default='Super Admin', max_length=40)),
                ('status', models.CharField(default='Active', max_length=24)),
                ('last_active', models.CharField(max_length=80)),
                ('password_salt', models.CharField(max_length=128)),
                ('password_hash', models.CharField(max_length=256)),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rp_platform_admins',
            },
        ),
        migrations.CreateModel(
            name='PlatformSession',
            fields=[
                ('access_token_hash', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rp_platform_sessions',
            },
        ),
        migrations.RemoveIndex(
            model_name='sessiontoken',
            name='rp_sessions_user_id_1f7ded_idx',
        ),
        migrations.AlterField(
            model_name='workspacerecord',
            name='row_id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='platformadmin',
            index=models.Index(fields=['email_normalized'], name='rp_platform_email_n_bf4949_idx'),
        ),
        migrations.AddIndex(
            model_name='platformadmin',
            index=models.Index(fields=['role'], name='rp_platform_role_6c04f2_idx'),
        ),
        migrations.AddIndex(
            model_name='platformadmin',
            index=models.Index(fields=['status'], name='rp_platform_status_375a95_idx'),
        ),
        migrations.AddField(
            model_name='platformsession',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='rhinopeak.platformadmin'),
        ),
        migrations.AddIndex(
            model_name='platformsession',
            index=models.Index(fields=['admin'], name='rp_platform_admin_i_c674dd_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsession',
            index=models.Index(fields=['expires_at'], name='rp_platform_expires_f28c83_idx'),
        ),
        migrations.AddIndex(
            model_name='platformsession',
            index=models.Index(fields=['revoked_at'], name='rp_platform_revoked_966e7d_idx'),
        ),
    ]
