enum AppLanguage { en, ne }

extension AppLanguageCode on AppLanguage {
  String get code => this == AppLanguage.ne ? 'ne' : 'en';
}

AppLanguage languageFromCode(String? value) {
  return value == 'ne' ? AppLanguage.ne : AppLanguage.en;
}

class AppStrings {
  static String tr(AppLanguage language, String key) {
    return _strings[language.code]?[key] ?? _strings['en']?[key] ?? key;
  }

  static String trValue(AppLanguage language, String value) {
    final trimmed = value.trim();
    if (trimmed.isEmpty) return value;
    final direct = tr(language, trimmed);
    if (direct != trimmed) return direct;
    final lower = trimmed.toLowerCase();
    final lowerValue = _strings[language.code]?[lower] ?? _strings['en']?[lower];
    return lowerValue ?? value;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'appName': 'RhinoPeak Business',
      'loginTitle': 'Log in to your workspace',
      'registerTitle': 'Create your workspace',
      'loginSubtitle':
          'Review sales, stock, customers, credit, and daily cash from your phone.',
      'registerSubtitle':
          'Set up your business, team, stock, and bills in one mobile workspace.',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'phone': 'Phone',
      'businessName': 'Business name',
      'login': 'Log in',
      'register': 'Create account',
      'forgotPassword': 'Reset password',
      'switchToRegister': 'New business? Create account',
      'switchToLogin': 'Already registered? Log in',
      'home': 'Home',
      'sales': 'Sales',
      'quickAdd': 'Quick Add',
      'stock': 'Stock',
      'more': 'More',
      'dashboard': 'Dashboard',
      'todayRevenue': "Today's revenue",
      'monthlyRevenue': 'Monthly revenue',
      'creditDue': 'Credit due',
      'lowStock': 'Low stock',
      'totalItems': 'Total items',
      'noProductsMatch': 'No products match',
      'limit': 'Limit',
      'assistant': 'Assistant',
      'aiAssistant': 'AI assistant',
      'aiAssistantHelp': 'Ask business questions or create safe draft actions.',
      'assistantWelcome':
          'Hello! I am your RhinoPeak AI assistant. Ask about sales, expenses, stock, customer balance, or create a safe draft action.',
      'assistantInputHint': 'Ask or type a command...',
      'assistantSuggestionRevenue': 'Revenue today',
      'assistantSuggestionExpense': 'Add expense',
      'assistantSuggestionStock': 'Show low stock',
      'assistantSuggestionBalance': 'Customer balance',
      'I could not understand that.': 'I could not understand that.',
      'Opening the bill scanner. Take a clear photo, then review the extracted fields.':
          'Opening the bill scanner. Take a clear photo, then review the extracted fields.',
      'Opening the right page now.': 'Opening the right page now.',
      'I prepared this action. Review it once, then confirm to save it.':
          'I prepared this action. Review it once, then confirm to save it.',
      'I can open the right page for this task and keep the user in control.':
          'I can open the right page for this task and keep the user in control.',
      'Command executed successfully.': 'Command executed successfully.',
      'listening': 'Listening...',
      'trySpeaking': 'Try speaking one of these:',
      'operationCancelled': 'Operation cancelled.',
      'confirmAction': 'Confirm action',
      'confirmNewExpense': 'Confirm new expense',
      'confirmNewCustomer': 'Confirm new customer',
      'confirmNewSupplier': 'Confirm new supplier',
      'confirmNewProduct': 'Confirm new product',
      'confirmAndSave': 'Confirm & save',
      'initialStock': 'Initial stock',
      'scanBillDashboardHelp': 'Capture supplier bills, VAT invoices, or receipts and save them after review.',
      'openAssistant': 'Open assistant',
      'reviewAndSave': 'Review and save',
      'customers': 'Customers',
      'orders': 'Orders',
      'addSale': 'Add sale',
      'addExpense': 'Add expense',
      'addStock': 'Add stock',
      'scanBill': 'Scan bill',
      'scanBillHelp': 'Paste bill text, review fields, then save to records.',
      'ocrText': 'Bill text',
      'parseBill': 'Read bill',
      'reviewBill': 'Review bill',
      'shopVendor': 'Shop or vendor',
      'billNumber': 'Bill number',
      'billDate': 'Bill date',
      'saveAs': 'Save as',
      'saveToRecords': 'Save to records',
      'items': 'Items',
      'addItem': 'Add item',
      'lineTotal': 'Line total',
      'sampleBill': 'Use sample',
      'scannedBills': 'Scanned bills',
      'savedBillScan': 'Bill saved to records.',
      'customGptPipeline': 'Custom GPT Pipeline',
      'uploadingImage': 'Uploading invoice image',
      'runningOcr': 'Running character OCR extraction',
      'llmStructuring': 'LLM Structuring (Custom PyTorch GPT)',
      'validatingRules': 'Applying mathematical validation rules',
      'selectTemplateToSimulate': 'Select a receipt template to simulate mobile capture',
      'simulatedView': 'Simulated Camera Viewfinder',
      'customGptNotes': 'Parsed & structured by custom character-level GPT model.',
      'addProduct': 'Add product',
      'addCategory': 'Add Category',
      'customerName': 'Customer name',
      'product': 'Product',
      'quantity': 'Quantity',
      'unit': 'Unit',
      'price': 'Price',
      'tax': 'Tax',
      'payment': 'Payment',
      'cash': 'Cash',
      'Cash': 'Cash',
      'credit': 'Credit',
      'Credit': 'Credit',
      'online': 'Online',
      'Online': 'Online',
      'Bank': 'Bank',
      'Wallet': 'Wallet',
      'Completed': 'Completed',
      'Pending': 'Pending',
      'Draft': 'Draft',
      'Parsed': 'Parsed',
      'Approved': 'Approved',
      'marketing': 'Marketing',
      'General': 'General',
      'rent': 'Rent',
      'salary': 'Salary',
      'transport': 'Transport',
      'repair': 'Repair',
      'utilities': 'Utilities',
      'save': 'Save',
      'cancel': 'Cancel',
      'inventory': 'Inventory',
      'category': 'Category',
      'supplier': 'Supplier',
      'suppliers': 'Suppliers',
      'parties': 'Parties',
      'purchases': 'Purchases',
      'cashBank': 'Cash & Bank',
      'accounting': 'Accounting',
      'documents': 'Documents',
      'reminders': 'Reminders',
      'teamRoles': 'Team & Roles',
      'audit': 'Audit',
      'syncLog': 'Sync Log',
      'support': 'Support',
      'reorder': 'Reorder',
      'expenseCategory': 'Expense category',
      'expenses': 'Expenses',
      'vendor': 'Vendor',
      'amount': 'Amount',
      'cost': 'Cost',
      'total': 'Total',
      'reason': 'Reason',
      'note': 'Note',
      'stockIn': 'Stock In',
      'stockOut': 'Stock Out',
      'correction': 'Correction',
      'creditCustomers': 'Credit customers',
      'bills': 'Bills',
      'reports': 'Reports',
      'billing': 'Billing',
      'plan': 'Plan',
      'currency': 'Currency',
      'invoicePrefix': 'Invoice prefix',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'nepali': 'Nepali',
      'sync': 'Sync',
      'add': 'Add',
      'addNew': 'Add new',
      'view': 'View',
      'edit': 'Edit',
      'delete': 'Delete',
      'actions': 'Actions',
      'deleteRecordTitle': 'Delete record?',
      'deleteRecordBody':
          'This will remove the selected record from this workspace.',
      'dbOnline': 'Backend online',
      'offlineReady': 'Offline cache ready',
      'logout': 'Logout',
      'emptySales': 'No sales yet. Add the first sale from Quick Add.',
      'emptyStock': 'No products yet. Add milk, grocery, or service items.',
      'easySaleHelp': 'Use simple daily sale entry. Add buyer later if needed.',
      'addProductHelp':
          'Add any item: milk in liters, rice in kg, or services.',
      'categoryCrud': 'Category CRUD',
      'categoryHelp':
          'Create simple names staff understand, like Dairy, Grocery, or Repair.',
      'customerModuleHelp': 'Customer profiles and credit history',
      'supplierModuleHelp': 'Supplier list and purchase history',
      'creditModuleHelp': 'Credit customers and due amount',
      'partiesModuleHelp': 'Customers and suppliers in one ledger',
      'purchasesModuleHelp': 'Supplier bills, received stock, and payables',
      'expensesModuleHelp': 'Daily costs and VAT input',
      'cashBankModuleHelp': 'Cash, bank, wallet balance, and movements',
      'accountingModuleHelp': 'Journal entries and Nepal VAT view',
      'billsModuleHelp': 'Print and download customer bills',
      'documentsModuleHelp': 'Receipts, invoices, and attachments',
      'remindersModuleHelp': 'Payment follow-ups and reminder history',
      'reportsModuleHelp': 'Sales, stock, tax, and profit reports',
      'billingModuleHelp': 'Plan, invoices, and upgrade',
      'teamModuleHelp': 'Users, roles, and permissions',
      'auditModuleHelp': 'Track every important action',
      'syncModuleHelp': 'Offline and device sync activity',
      'supportModuleHelp': 'Help tickets and platform messages',
      'settingsModuleHelp': 'Language, tax, invoice, and profile',
      'mobileExpansion':
          'This module is available on the web portal and ready for mobile expansion.',
      'saved': 'Saved successfully.',
      'passwordResetSent': 'Password reset request sent.',
      'required': 'Please fill required fields.',
      'dailyOperations': 'Daily Operations',
      'financialsLedgers': 'Financials & Ledgers',
      'analyticsReminders': 'Analytics & Reminders',
      'systemAdmin': 'System Administration',
      // Analytics page
      'revenueLabel': 'Revenue',
      'unitsSold': 'Units Sold',
      'profitMargin': 'Profit Margin',
      'revenueTrend': 'Revenue Trend',
      'currentPeriod': 'Current Period',
      'previousPeriod': 'Previous Period',
      'productPerformance': 'Product Performance',
      'revenueByCategory': 'Revenue by Category',
      'customerSplit': 'Customer Split',
      'repeatCustomers': 'Repeat',
      'newCustomers': 'New',
      'customerLTV': 'Customer Lifetime Value',
      'ltvBelow25k': 'Below NPR 25K',
      'ltv25kTo100k': 'NPR 25K–100K',
      'ltv100kTo250k': 'NPR 100K–250K',
      'ltvOver250k': 'Over NPR 250K',
      'salesHeatmap': 'Sales Heatmap',
      'last7days': 'Last 7 days',
      'last30days': 'Last 30 days',
      'last90days': 'Last 90 days',
      // Reports page
      'generateReport': 'Generate Report',
      'reportTitle': 'Report Title',
      'reportType': 'Report Type',
      'reportTemplate': 'Template',
      'dateRange': 'Date Range',
      'scheduleReport': 'Schedule Report',
      'reportExecutive': 'Executive',
      'reportSales': 'Sales',
      'reportInventory': 'Inventory',
      'reportAccounting': 'Accounting',
      'noReports': 'No reports yet.',
      'reportReady': 'Ready',
      'reportDraft': 'Draft',
      'reportScheduled': 'Scheduled',
      // Bill scanner confidence
      'lowConfidenceWarning': 'Low confidence — please review this field',
      'mathMismatchWarning': 'Math mismatch — totals do not add up',
      'ID': 'ID',
      'Date': 'Date',
      'Payment': 'Payment',
      'Category': 'Category',
      'Type': 'Type',
      'Status': 'Status',
      'entries': 'entries',
      'accounts': 'accounts',
      'account': 'account',
      'voucher': 'voucher',
      'categories': 'categories',
      'permissions': 'permissions',
      'products': 'products',
      'files': 'files',
      'Active': 'Active',
      'Ready': 'Ready',
      'Sent': 'Sent',
      'User': 'User',
      'Feature': 'Feature',
      'Open': 'Open',
      'Customer': 'Customer',
      'Supplier': 'Supplier',
      'Both': 'Both',
      'Receipt': 'Receipt',
      'Payment Received': 'Payment Received',
      'Payment Paid': 'Payment Paid',
      'Sale Credit': 'Sale Credit',
      'Purchase Credit': 'Purchase Credit',
      'Deposit': 'Deposit',
      'Withdrawal': 'Withdrawal',
      'Not added': 'Not added',
      'No notes': 'No notes',
      'No note': 'No note',
      'No contact': 'No contact',
      'No vendor': 'No vendor',
      'Unknown account': 'Unknown account',
      'Not found': 'Not found',
      'No update yet': 'No update yet',
      'Details': 'Details',
      'RatoPanda Mart': 'RatoPanda Mart',
      'Buffalo Milk': 'Buffalo Milk',
      'Basmati Rice 25kg': 'Basmati Rice 25kg',
      'Instant Noodles': 'Instant Noodles',
      'CTC Tea 500g': 'CTC Tea 500g',
      'Himal Dairy Suppliers': 'Himal Dairy Suppliers',
      'Everest Wholesale': 'Everest Wholesale',
      'Sita Kirana': 'Sita Kirana',
      'Hari Cafe': 'Hari Cafe',
      'Maya Store': 'Maya Store',
      'Walk-in customer': 'Walk-in customer',
      'Shop cash': 'Shop cash',
      'Shop cash drawer': 'Shop cash drawer',
      'Nabil Bank': 'Nabil Bank',
      'Nabil Bank current': 'Nabil Bank current',
      'eSewa wallet': 'eSewa wallet',
      'Dairy': 'Dairy',
      'Grocery': 'Grocery',
      'Snacks': 'Snacks',
      'Beverage': 'Beverage',
      'Household': 'Household',
      'In Stock': 'In Stock',
      'Low Stock': 'Low Stock',
      'Out of Stock': 'Out of Stock',
      'Marketing': 'Marketing',
      'Fuel': 'Fuel',
      'Facebook boost': 'Facebook boost',
      'Monthly shop rent': 'Monthly shop rent',
      'Weekend promotion': 'Weekend promotion',
      'Delivery bike': 'Delivery bike',
      'House owner': 'House owner',
      'Monthly rent': 'Monthly rent',
      'Fuel expense': 'Fuel expense',
      'Rice supplier payment': 'Rice supplier payment',
      'Cash sale': 'Cash sale',
      'Milk purchase payable': 'Milk purchase payable',
      'liter': 'liter',
      'ltr': 'liter',
      'L': 'liter',
      'bag': 'bag',
      'packet': 'packet',
      'pkt': 'packet',
      'pcs': 'pcs',
      'kg': 'kg',
      'gm': 'gm',
      'meter': 'meter',
      'service': 'service',
      'Cold shelf': 'Cold shelf',
      'Aisle 1': 'Aisle 1',
      'Aisle 2': 'Aisle 2',
      'Morning delivery.': 'Morning delivery.',
      'Weekly bulk supply.': 'Weekly bulk supply.',
      'Supplier payable.': 'Supplier payable.',
      'Buys dairy every morning.': 'Buys dairy every morning.',
      'Pays weekly.': 'Pays weekly.',
      'Prefers FonePay.': 'Prefers FonePay.',
      'No related records yet. New sales, payments, stock logs, and documents will appear here.':
          'No related records yet. New sales, payments, stock logs, and documents will appear here.',
    },
    'ne': {
      'appName': 'राइनोपिक बिजनेस',
      'loginTitle': 'आफ्नो कार्यस्थानमा लग इन गर्नुहोस्',
      'registerTitle': 'नयाँ कार्यस्थान बनाउनुहोस्',
      'loginSubtitle':
          'फोनबाट बिक्री, स्टक, ग्राहक, उधारो र दैनिक नगद हेर्नुहोस्।',
      'registerSubtitle':
          'व्यवसाय, टिम, स्टक र बिल सबै एउटै मोबाइल कार्यस्थानमा मिलाउनुहोस्।',
      'email': 'इमेल',
      'password': 'पासवर्ड',
      'name': 'नाम',
      'phone': 'फोन',
      'businessName': 'व्यवसायको नाम',
      'login': 'लग इन',
      'register': 'खाता बनाउनुहोस्',
      'forgotPassword': 'पासवर्ड रिसेट',
      'switchToRegister': 'नयाँ व्यवसाय? खाता बनाउनुहोस्',
      'switchToLogin': 'पहिले नै खाता छ? लग इन',
      'home': 'होम',
      'sales': 'बिक्री',
      'quickAdd': 'छिटो थप्नुहोस्',
      'stock': 'स्टक',
      'more': 'थप',
      'dashboard': 'ड्यासबोर्ड',
      'todayRevenue': 'आजको आम्दानी',
      'monthlyRevenue': 'महिनाको आम्दानी',
      'creditDue': 'उधारो बाँकी',
      'lowStock': 'कम स्टक',
      'totalItems': 'कुल सामान',
      'noProductsMatch': 'मिल्ने सामान छैन',
      'limit': 'सीमा',
      'assistant': 'सहायक',
      'aiAssistant': 'AI सहायक',
      'aiAssistantHelp': 'व्यवसायका प्रश्न सोध्नुहोस् वा सुरक्षित ड्राफ्ट काम बनाउनुहोस्।',
      'assistantWelcome':
          'नमस्ते! म तपाईंको RhinoPeak AI सहायक हुँ। बिक्री, खर्च, स्टक, ग्राहक बाँकी सोध्नुहोस् वा सुरक्षित ड्राफ्ट काम बनाउनुहोस्।',
      'assistantInputHint': 'प्रश्न वा काम लेख्नुहोस्...',
      'assistantSuggestionRevenue': 'आजको आम्दानी',
      'assistantSuggestionExpense': 'खर्च थप्नुहोस्',
      'assistantSuggestionStock': 'कम स्टक हेर्नुहोस्',
      'assistantSuggestionBalance': 'ग्राहक बाँकी',
      'I could not understand that.': 'मैले त्यो बुझ्न सकिनँ।',
      'Opening the bill scanner. Take a clear photo, then review the extracted fields.':
          'बिल स्क्यानर खुल्दैछ। स्पष्ट फोटो लिनुहोस्, अनि निकालिएका विवरण जाँच गर्नुहोस्।',
      'Opening the right page now.': 'ठीक पेज खुल्दैछ।',
      'I prepared this action. Review it once, then confirm to save it.':
          'मैले यो काम तयार गरें। एक पटक जाँच गरेर सेभ गर्न पुष्टि गर्नुहोस्।',
      'I can open the right page for this task and keep the user in control.':
          'यो कामका लागि सही पेज खोल्न सक्छु, नियन्त्रण तपाईंमै रहन्छ।',
      'Command executed successfully.': 'काम सफलतापूर्वक पूरा भयो।',
      'listening': 'सुन्दैछ...',
      'trySpeaking': 'यीमध्ये एउटा बोल्नुहोस्:',
      'operationCancelled': 'काम रद्द भयो।',
      'confirmAction': 'काम पुष्टि गर्नुहोस्',
      'confirmNewExpense': 'नयाँ खर्च पुष्टि',
      'confirmNewCustomer': 'नयाँ ग्राहक पुष्टि',
      'confirmNewSupplier': 'नयाँ सप्लायर पुष्टि',
      'confirmNewProduct': 'नयाँ सामान पुष्टि',
      'confirmAndSave': 'पुष्टि गरी सेभ',
      'initialStock': 'सुरुको स्टक',
      'scanBillDashboardHelp': 'सप्लायर बिल, VAT इनभ्वाइस वा रसिद स्क्यान गरेर जाँचपछि सेभ गर्नुहोस्।',
      'openAssistant': 'सहायक खोल्नुहोस्',
      'reviewAndSave': 'जाँच गरी सेभ',
      'customers': 'ग्राहक',
      'orders': 'अर्डर',
      'addSale': 'बिक्री थप्नुहोस्',
      'addExpense': 'खर्च थप्नुहोस्',
      'addStock': 'स्टक थप्नुहोस्',
      'scanBill': 'बिल स्क्यान',
      'scanBillHelp': 'बिलको टेक्स्ट राख्नुहोस्, विवरण जाँच गर्नुहोस्, अनि रेकर्डमा सेभ गर्नुहोस्।',
      'ocrText': 'बिल टेक्स्ट',
      'parseBill': 'बिल पढ्नुहोस्',
      'reviewBill': 'बिल जाँच',
      'shopVendor': 'पसल वा विक्रेता',
      'billNumber': 'बिल नम्बर',
      'billDate': 'बिल मिति',
      'saveAs': 'यस रूपमा सेभ',
      'saveToRecords': 'रेकर्डमा सेभ',
      'items': 'सामानहरू',
      'addItem': 'सामान थप्नुहोस्',
      'lineTotal': 'लाइन कुल',
      'sampleBill': 'नमुना प्रयोग गर्नुहोस्',
      'scannedBills': 'स्क्यान बिल',
      'savedBillScan': 'बिल रेकर्डमा सेभ भयो।',
      'customGptPipeline': 'कस्टम GPT पाइपलाइन',
      'uploadingImage': 'बिलको फोटो अपलोड हुँदैछ',
      'runningOcr': 'अक्षरहरू (OCR) निकाल्ने काम हुँदैछ',
      'llmStructuring': 'LLM संरचना (कस्टम PyTorch GPT)',
      'validatingRules': 'गणितीय प्रमाणीकरण नियमहरू लागू गरिँदैछ',
      'selectTemplateToSimulate': 'मोबाइल स्क्यान सिमुलेट गर्न रसिद नमुना छान्नुहोस्',
      'simulatedView': 'सिमुलेटेड क्यामेरा भ्युफाइन्डर',
      'customGptNotes': 'कस्टम क्यारेक्टर-स्तर GPT मोडेल द्वारा संरचित।',
      'addProduct': 'सामान थप्नुहोस्',
      'addCategory': 'वर्ग थप्नुहोस्',
      'customerName': 'ग्राहकको नाम',
      'product': 'सामान',
      'quantity': 'मात्रा',
      'unit': 'एकाइ',
      'price': 'मूल्य',
      'tax': 'कर',
      'payment': 'भुक्तानी',
      'cash': 'नगद',
      'Cash': 'नगद',
      'credit': 'उधारो',
      'Credit': 'उधारो',
      'online': 'अनलाइन',
      'Online': 'अनलाइन',
      'Bank': 'बैंक',
      'Wallet': 'वालेट',
      'Completed': 'पूरा भयो',
      'Pending': 'पेन्डिङ',
      'Draft': 'मस्यौदा',
      'Parsed': 'पढिएको',
      'Approved': 'स्वीकृत',
      'marketing': 'मार्केटिङ',
      'General': 'सामान्य',
      'rent': 'भाडा',
      'salary': 'तलब',
      'transport': 'यातायात',
      'repair': 'मर्मत',
      'utilities': 'बत्ती/पानी',
      'save': 'सेभ',
      'cancel': 'रद्द',
      'inventory': 'स्टक',
      'category': 'वर्ग',
      'supplier': 'सप्लायर',
      'suppliers': 'सप्लायरहरू',
      'parties': 'पार्टीहरू',
      'purchases': 'खरिद',
      'cashBank': 'नगद र बैंक',
      'accounting': 'लेखा',
      'documents': 'कागजात',
      'reminders': 'सम्झना',
      'teamRoles': 'टिम र भूमिका',
      'audit': 'अडिट',
      'syncLog': 'सिंक लग',
      'support': 'सहायता',
      'reorder': 'फेरि ल्याउने सीमा',
      'expenseCategory': 'खर्चको वर्ग',
      'expenses': 'खर्च',
      'vendor': 'कसलाई तिरियो',
      'amount': 'रकम',
      'cost': 'लागत',
      'total': 'जम्मा',
      'reason': 'कारण',
      'note': 'नोट',
      'stockIn': 'स्टक थपियो',
      'stockOut': 'स्टक घट्यो',
      'correction': 'सच्याइयो',
      'creditCustomers': 'उधारो ग्राहक',
      'bills': 'बिल',
      'reports': 'रिपोर्ट',
      'billing': 'बिलिङ',
      'plan': 'योजना',
      'currency': 'मुद्रा',
      'invoicePrefix': 'बिल नम्बर सुरु',
      'settings': 'सेटिङ',
      'language': 'भाषा',
      'english': 'अंग्रेजी',
      'nepali': 'नेपाली',
      'sync': 'सिंक',
      'add': 'थप्नुहोस्',
      'addNew': 'नयाँ थप्नुहोस्',
      'view': 'हेर्नुहोस्',
      'edit': 'सच्याउनुहोस्',
      'delete': 'हटाउनुहोस्',
      'actions': 'कामहरू',
      'deleteRecordTitle': 'रेकर्ड हटाउने?',
      'deleteRecordBody': 'यसले छानिएको रेकर्ड यो कार्यस्थानबाट हटाउँछ।',
      'dbOnline': 'ब्याकएन्ड अनलाइन',
      'offlineReady': 'अफलाइन क्यास तयार',
      'logout': 'लग आउट',
      'emptySales': 'अहिले बिक्री छैन। छिटो थप्नुहोस् बाट बिक्री राख्नुहोस्।',
      'emptyStock': 'अहिले सामान छैन। दूध, किराना वा सेवा सामान थप्नुहोस्।',
      'easySaleHelp':
          'सजिलो दैनिक बिक्री राख्नुहोस्। ग्राहक पछि पनि थप्न सकिन्छ।',
      'addProductHelp':
          'दूध लिटरमा, चामल केजीमा, वा सेवा जस्ता सामान थप्नुहोस्।',
      'categoryCrud': 'वर्ग बनाउने र हेर्ने',
      'categoryHelp':
          'स्टाफले बुझ्ने सरल नाम राख्नुहोस्, जस्तै डेरी, किराना वा मर्मत।',
      'customerModuleHelp': 'ग्राहक विवरण र उधारो इतिहास',
      'supplierModuleHelp': 'सप्लायर सूची र खरिद इतिहास',
      'creditModuleHelp': 'उधारो ग्राहक र बाँकी रकम',
      'partiesModuleHelp': 'ग्राहक र सप्लायर एउटै लेजरमा',
      'purchasesModuleHelp': 'सप्लायर बिल, आएको स्टक र तिर्नुपर्ने रकम',
      'expensesModuleHelp': 'दैनिक खर्च र भ्याट इनपुट',
      'cashBankModuleHelp': 'नगद, बैंक, वालेट ब्यालेन्स र कारोबार',
      'accountingModuleHelp': 'जर्नल इन्ट्री र नेपाल भ्याट दृश्य',
      'billsModuleHelp': 'ग्राहक बिल प्रिन्ट र डाउनलोड',
      'documentsModuleHelp': 'रसिद, बिल र अट्याचमेन्ट',
      'remindersModuleHelp': 'भुक्तानी फलोअप र सम्झना इतिहास',
      'reportsModuleHelp': 'बिक्री, स्टक, कर र नाफा रिपोर्ट',
      'billingModuleHelp': 'योजना, बिल र अपग्रेड',
      'teamModuleHelp': 'प्रयोगकर्ता, भूमिका र अनुमति',
      'auditModuleHelp': 'हरेक महत्वपूर्ण काम ट्र्याक गर्नुहोस्',
      'syncModuleHelp': 'अफलाइन र डिभाइस सिंक गतिविधि',
      'supportModuleHelp': 'सहायता टिकट र प्लेटफर्म सन्देश',
      'settingsModuleHelp': 'भाषा, कर, बिल र प्रोफाइल',
      'mobileExpansion':
          'यो सुविधा वेब पोर्टलमा उपलब्ध छ र मोबाइलमा विस्तार गर्न तयार छ।',
      'saved': 'सफलतापूर्वक सेभ भयो।',
      'passwordResetSent': 'पासवर्ड रिसेट अनुरोध पठाइयो।',
      'required': 'आवश्यक विवरण भर्नुहोस्।',
      'dailyOperations': 'दैनिक सञ्चालन',
      'financialsLedgers': 'वित्तीय र खाताहरू',
      'analyticsReminders': 'विश्लेषण र अनुस्मारकहरू',
      'systemAdmin': 'प्रणाली प्रशासन',
      // Analytics page
      'revenueLabel': 'आम्दानी',
      'unitsSold': 'बेचिएका इकाइहरू',
      'profitMargin': 'नाफा मार्जिन',
      'revenueTrend': 'आम्दानी प्रवृत्ति',
      'currentPeriod': 'यो अवधि',
      'previousPeriod': 'अघिल्लो अवधि',
      'productPerformance': 'उत्पादन प्रदर्शन',
      'revenueByCategory': 'वर्गअनुसार आम्दानी',
      'customerSplit': 'ग्राहक विभाजन',
      'repeatCustomers': 'दोहोरो',
      'newCustomers': 'नयाँ',
      'customerLTV': 'ग्राहक जीवनकाल मूल्य',
      'ltvBelow25k': 'NPR २५K भन्दा कम',
      'ltv25kTo100k': 'NPR २५K–१००K',
      'ltv100kTo250k': 'NPR १००K–२५०K',
      'ltvOver250k': 'NPR २५०K माथि',
      'salesHeatmap': 'बिक्री हिटम्याप',
      'last7days': 'पछिल्लो ७ दिन',
      'last30days': 'पछिल्लो ३० दिन',
      'last90days': 'पछिल्लो ९० दिन',
      // Reports page
      'generateReport': 'रिपोर्ट बनाउनुहोस्',
      'reportTitle': 'रिपोर्ट शीर्षक',
      'reportType': 'रिपोर्ट प्रकार',
      'reportTemplate': 'ढाँचा',
      'dateRange': 'मिति दायरा',
      'scheduleReport': 'रिपोर्ट तालिका',
      'reportExecutive': 'कार्यकारी',
      'reportSales': 'बिक्री',
      'reportInventory': 'सूची',
      'reportAccounting': 'लेखा',
      'noReports': 'अहिलेसम्म कुनै रिपोर्ट छैन।',
      'reportReady': 'तयार',
      'reportDraft': 'मस्यौदा',
      'reportScheduled': 'तालिका गरिएको',
      // Bill scanner confidence
      'lowConfidenceWarning': 'कम भरोसा — यो क्षेत्र जाँच गर्नुहोस्',
      'mathMismatchWarning': 'गणना मेल खाएन — कुल जोड मिलेन',
      'ID': 'आईडी',
      'Date': 'मिति',
      'Payment': 'भुक्तानी',
      'Category': 'श्रेणी',
      'Type': 'प्रकार',
      'Status': 'स्थिति',
      'entries': 'प्रविष्टि',
      'accounts': 'खाता',
      'account': 'खाता',
      'voucher': 'भौचर',
      'categories': 'श्रेणी',
      'permissions': 'अनुमति',
      'products': 'सामान',
      'files': 'फाइल',
      'Active': 'सक्रिय',
      'Ready': 'तयार',
      'Sent': 'पठाइयो',
      'User': 'प्रयोगकर्ता',
      'Feature': 'सुविधा',
      'Open': 'खुला',
      'Customer': 'ग्राहक',
      'Supplier': 'सप्लायर',
      'Both': 'दुवै',
      'Receipt': 'रसिद',
      'Payment Received': 'भुक्तानी प्राप्त',
      'Payment Paid': 'भुक्तानी गरिएको',
      'Sale Credit': 'उधारो बिक्री',
      'Purchase Credit': 'उधारो खरिद',
      'Deposit': 'जम्मा',
      'Withdrawal': 'निकासी',
      'Not added': 'थपिएको छैन',
      'No notes': 'नोट छैन',
      'No note': 'नोट छैन',
      'No contact': 'सम्पर्क छैन',
      'No vendor': 'भेन्डर छैन',
      'Unknown account': 'अज्ञात खाता',
      'Not found': 'फेला परेन',
      'No update yet': 'अहिलेसम्म अपडेट छैन',
      'Details': 'विवरण',
      'RatoPanda Mart': 'रातोपान्डा मार्ट',
      'Buffalo Milk': 'भैंसीको दूध',
      'Basmati Rice 25kg': 'बासमती चामल २५ केजी',
      'Instant Noodles': 'इन्स्ट्यान्ट चाउचाउ',
      'CTC Tea 500g': 'CTC चिया ५०० ग्राम',
      'Himal Dairy Suppliers': 'हिमाल डेरी सप्लायर्स',
      'Everest Wholesale': 'एभरेस्ट होलसेल',
      'Sita Kirana': 'सीता किराना',
      'Hari Cafe': 'हरि क्याफे',
      'Maya Store': 'माया स्टोर',
      'Walk-in customer': 'वाक-इन ग्राहक',
      'Shop cash': 'पसल नगद',
      'Shop cash drawer': 'पसल नगद दराज',
      'Nabil Bank': 'नबिल बैंक',
      'Nabil Bank current': 'नबिल बैंक करेन्ट',
      'eSewa wallet': 'ईसेवा वालेट',
      'Dairy': 'डेरी',
      'Grocery': 'किराना',
      'Snacks': 'स्न्याक्स',
      'Beverage': 'पेय पदार्थ',
      'Household': 'घरायसी',
      'In Stock': 'स्टकमा छ',
      'Low Stock': 'कम स्टक',
      'Out of Stock': 'स्टक सकियो',
      'Marketing': 'मार्केटिङ',
      'Fuel': 'इन्धन',
      'Facebook boost': 'फेसबुक बुस्ट',
      'Monthly shop rent': 'मासिक पसल भाडा',
      'Weekend promotion': 'सप्ताहन्त प्रमोसन',
      'Delivery bike': 'डेलिभरी बाइक',
      'House owner': 'घरधनी',
      'Monthly rent': 'मासिक भाडा',
      'Fuel expense': 'इन्धन खर्च',
      'Rice supplier payment': 'चामल सप्लायर भुक्तानी',
      'Cash sale': 'नगद बिक्री',
      'Milk purchase payable': 'दूध खरिद तिर्नुपर्ने',
      'liter': 'लिटर',
      'ltr': 'लिटर',
      'L': 'लिटर',
      'bag': 'बोरा',
      'packet': 'प्याकेट',
      'pkt': 'प्याकेट',
      'pcs': 'गोटा',
      'kg': 'केजी',
      'gm': 'ग्राम',
      'meter': 'मिटर',
      'service': 'सेवा',
      'Cold shelf': 'चिसो शेल्फ',
      'Aisle 1': 'आइल १',
      'Aisle 2': 'आइल २',
      'Morning delivery.': 'बिहान डेलिभरी।',
      'Weekly bulk supply.': 'साप्ताहिक थोक आपूर्ति।',
      'Supplier payable.': 'सप्लायरलाई तिर्नुपर्ने।',
      'Buys dairy every morning.': 'हरेक बिहान डेरी सामान किन्छ।',
      'Pays weekly.': 'साप्ताहिक भुक्तानी गर्छ।',
      'Prefers FonePay.': 'FonePay रुचाउँछ।',
      'No related records yet. New sales, payments, stock logs, and documents will appear here.':
          'अहिलेसम्म सम्बन्धित रेकर्ड छैन। नयाँ बिक्री, भुक्तानी, स्टक लग र कागजात यहाँ देखिन्छन्।',
    },
  };
}
