enum AppLanguage { en, ne }

extension AppLanguageCode on AppLanguage {
  String get code => this == AppLanguage.ne ? 'ne' : 'en';
}

AppLanguage languageFromCode(String? value) {
  return value == 'ne' ? AppLanguage.ne : AppLanguage.en;
}

class AppStrings {
  static String tr(AppLanguage language, String key) {
    return _strings[language.code]?[key] ?? _strings['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'appName': 'RhinoPeak Business',
      'loginTitle': 'Log in to your workspace',
      'registerTitle': 'Create your workspace',
      'loginSubtitle':
          'Review sales, stock, customers, credit, and daily cash from your phone.',
      'registerSubtitle':
          'Set up your business, team, stock, and bills in one mobile workspace.',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'businessName': 'Business name',
      'login': 'Log in',
      'register': 'Create account',
      'forgotPassword': 'Reset password',
      'switchToRegister': 'New business? Create account',
      'switchToLogin': 'Already registered? Log in',
      'home': 'Home',
      'sales': 'Sales',
      'quickAdd': 'Quick Add',
      'stock': 'Stock',
      'more': 'More',
      'dashboard': 'Dashboard',
      'todayRevenue': "Today's revenue",
      'monthlyRevenue': 'Monthly revenue',
      'creditDue': 'Credit due',
      'lowStock': 'Low stock',
      'customers': 'Customers',
      'orders': 'Orders',
      'addSale': 'Add sale',
      'addExpense': 'Add expense',
      'addStock': 'Add stock',
      'addProduct': 'Add product',
      'customerName': 'Customer name',
      'product': 'Product',
      'quantity': 'Quantity',
      'unit': 'Unit',
      'price': 'Price',
      'tax': 'Tax',
      'payment': 'Payment',
      'cash': 'Cash',
      'credit': 'Credit',
      'online': 'Online',
      'marketing': 'Marketing',
      'rent': 'Rent',
      'salary': 'Salary',
      'transport': 'Transport',
      'repair': 'Repair',
      'utilities': 'Utilities',
      'save': 'Save',
      'cancel': 'Cancel',
      'inventory': 'Inventory',
      'category': 'Category',
      'supplier': 'Supplier',
      'suppliers': 'Suppliers',
      'parties': 'Parties',
      'purchases': 'Purchases',
      'cashBank': 'Cash & Bank',
      'accounting': 'Accounting',
      'documents': 'Documents',
      'reminders': 'Reminders',
      'teamRoles': 'Team & Roles',
      'audit': 'Audit',
      'syncLog': 'Sync Log',
      'support': 'Support',
      'reorder': 'Reorder',
      'expenseCategory': 'Expense category',
      'expenses': 'Expenses',
      'vendor': 'Vendor',
      'amount': 'Amount',
      'cost': 'Cost',
      'total': 'Total',
      'reason': 'Reason',
      'note': 'Note',
      'stockIn': 'Stock In',
      'stockOut': 'Stock Out',
      'correction': 'Correction',
      'creditCustomers': 'Credit customers',
      'bills': 'Bills',
      'reports': 'Reports',
      'billing': 'Billing',
      'plan': 'Plan',
      'currency': 'Currency',
      'invoicePrefix': 'Invoice prefix',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'nepali': 'Nepali',
      'sync': 'Sync',
      'dbOnline': 'Backend online',
      'offlineReady': 'Offline cache ready',
      'logout': 'Logout',
      'emptySales': 'No sales yet. Add the first sale from Quick Add.',
      'emptyStock': 'No products yet. Add milk, grocery, or service items.',
      'easySaleHelp': 'Use simple daily sale entry. Add buyer later if needed.',
      'addProductHelp':
          'Add any item: milk in liters, rice in kg, or services.',
      'categoryCrud': 'Category CRUD',
      'categoryHelp':
          'Create simple names staff understand, like Dairy, Grocery, or Repair.',
      'customerModuleHelp': 'Customer profiles and credit history',
      'supplierModuleHelp': 'Supplier list and purchase history',
      'creditModuleHelp': 'Credit customers and due amount',
      'partiesModuleHelp': 'Customers and suppliers in one ledger',
      'purchasesModuleHelp': 'Supplier bills, received stock, and payables',
      'expensesModuleHelp': 'Daily costs and VAT input',
      'cashBankModuleHelp': 'Cash, bank, wallet balance, and movements',
      'accountingModuleHelp': 'Journal entries and Nepal VAT view',
      'billsModuleHelp': 'Print and download customer bills',
      'documentsModuleHelp': 'Receipts, invoices, and attachments',
      'remindersModuleHelp': 'Payment follow-ups and reminder history',
      'reportsModuleHelp': 'Sales, stock, tax, and profit reports',
      'billingModuleHelp': 'Plan, invoices, and upgrade',
      'teamModuleHelp': 'Users, roles, and permissions',
      'auditModuleHelp': 'Track every important action',
      'syncModuleHelp': 'Offline and device sync activity',
      'supportModuleHelp': 'Help tickets and platform messages',
      'settingsModuleHelp': 'Language, tax, invoice, and profile',
      'mobileExpansion':
          'This module is available on the web portal and ready for mobile expansion.',
      'saved': 'Saved successfully.',
      'passwordResetSent': 'Password reset request sent.',
      'required': 'Please fill required fields.',
      'dailyOperations': 'Daily Operations',
      'financialsLedgers': 'Financials & Ledgers',
      'analyticsReminders': 'Analytics & Reminders',
      'systemAdmin': 'System Administration',
    },
    'ne': {
      'appName': 'राइनोपिक बिजनेस',
      'loginTitle': 'आफ्नो कार्यस्थानमा लग इन गर्नुहोस्',
      'registerTitle': 'नयाँ कार्यस्थान बनाउनुहोस्',
      'loginSubtitle':
          'फोनबाट बिक्री, स्टक, ग्राहक, उधारो र दैनिक नगद हेर्नुहोस्।',
      'registerSubtitle':
          'व्यवसाय, टिम, स्टक र बिल सबै एउटै मोबाइल कार्यस्थानमा मिलाउनुहोस्।',
      'email': 'इमेल',
      'password': 'पासवर्ड',
      'name': 'नाम',
      'businessName': 'व्यवसायको नाम',
      'login': 'लग इन',
      'register': 'खाता बनाउनुहोस्',
      'forgotPassword': 'पासवर्ड रिसेट',
      'switchToRegister': 'नयाँ व्यवसाय? खाता बनाउनुहोस्',
      'switchToLogin': 'पहिले नै खाता छ? लग इन',
      'home': 'होम',
      'sales': 'बिक्री',
      'quickAdd': 'छिटो थप्नुहोस्',
      'stock': 'स्टक',
      'more': 'थप',
      'dashboard': 'ड्यासबोर्ड',
      'todayRevenue': 'आजको आम्दानी',
      'monthlyRevenue': 'महिनाको आम्दानी',
      'creditDue': 'उधारो बाँकी',
      'lowStock': 'कम स्टक',
      'customers': 'ग्राहक',
      'orders': 'अर्डर',
      'addSale': 'बिक्री थप्नुहोस्',
      'addExpense': 'खर्च थप्नुहोस्',
      'addStock': 'स्टक थप्नुहोस्',
      'addProduct': 'सामान थप्नुहोस्',
      'customerName': 'ग्राहकको नाम',
      'product': 'सामान',
      'quantity': 'मात्रा',
      'unit': 'एकाइ',
      'price': 'मूल्य',
      'tax': 'कर',
      'payment': 'भुक्तानी',
      'cash': 'नगद',
      'credit': 'उधारो',
      'online': 'अनलाइन',
      'marketing': 'मार्केटिङ',
      'rent': 'भाडा',
      'salary': 'तलब',
      'transport': 'यातायात',
      'repair': 'मर्मत',
      'utilities': 'बत्ती/पानी',
      'save': 'सेभ',
      'cancel': 'रद्द',
      'inventory': 'स्टक',
      'category': 'वर्ग',
      'supplier': 'सप्लायर',
      'suppliers': 'सप्लायरहरू',
      'parties': 'पार्टीहरू',
      'purchases': 'खरिद',
      'cashBank': 'नगद र बैंक',
      'accounting': 'लेखा',
      'documents': 'कागजात',
      'reminders': 'सम्झना',
      'teamRoles': 'टिम र भूमिका',
      'audit': 'अडिट',
      'syncLog': 'सिंक लग',
      'support': 'सहायता',
      'reorder': 'फेरि ल्याउने सीमा',
      'expenseCategory': 'खर्चको वर्ग',
      'expenses': 'खर्च',
      'vendor': 'कसलाई तिरियो',
      'amount': 'रकम',
      'cost': 'लागत',
      'total': 'जम्मा',
      'reason': 'कारण',
      'note': 'नोट',
      'stockIn': 'स्टक थपियो',
      'stockOut': 'स्टक घट्यो',
      'correction': 'सच्याइयो',
      'creditCustomers': 'उधारो ग्राहक',
      'bills': 'बिल',
      'reports': 'रिपोर्ट',
      'billing': 'बिलिङ',
      'plan': 'योजना',
      'currency': 'मुद्रा',
      'invoicePrefix': 'बिल नम्बर सुरु',
      'settings': 'सेटिङ',
      'language': 'भाषा',
      'english': 'अंग्रेजी',
      'nepali': 'नेपाली',
      'sync': 'सिंक',
      'dbOnline': 'ब्याकएन्ड अनलाइन',
      'offlineReady': 'अफलाइन क्यास तयार',
      'logout': 'लग आउट',
      'emptySales': 'अहिले बिक्री छैन। छिटो थप्नुहोस् बाट बिक्री राख्नुहोस्।',
      'emptyStock': 'अहिले सामान छैन। दूध, किराना वा सेवा सामान थप्नुहोस्।',
      'easySaleHelp':
          'सजिलो दैनिक बिक्री राख्नुहोस्। ग्राहक पछि पनि थप्न सकिन्छ।',
      'addProductHelp':
          'दूध लिटरमा, चामल केजीमा, वा सेवा जस्ता सामान थप्नुहोस्।',
      'categoryCrud': 'वर्ग बनाउने र हेर्ने',
      'categoryHelp':
          'स्टाफले बुझ्ने सरल नाम राख्नुहोस्, जस्तै डेरी, किराना वा मर्मत।',
      'customerModuleHelp': 'ग्राहक विवरण र उधारो इतिहास',
      'supplierModuleHelp': 'सप्लायर सूची र खरिद इतिहास',
      'creditModuleHelp': 'उधारो ग्राहक र बाँकी रकम',
      'partiesModuleHelp': 'ग्राहक र सप्लायर एउटै लेजरमा',
      'purchasesModuleHelp': 'सप्लायर बिल, आएको स्टक र तिर्नुपर्ने रकम',
      'expensesModuleHelp': 'दैनिक खर्च र भ्याट इनपुट',
      'cashBankModuleHelp': 'नगद, बैंक, वालेट ब्यालेन्स र कारोबार',
      'accountingModuleHelp': 'जर्नल इन्ट्री र नेपाल भ्याट दृश्य',
      'billsModuleHelp': 'ग्राहक बिल प्रिन्ट र डाउनलोड',
      'documentsModuleHelp': 'रसिद, बिल र अट्याचमेन्ट',
      'remindersModuleHelp': 'भुक्तानी फलोअप र सम्झना इतिहास',
      'reportsModuleHelp': 'बिक्री, स्टक, कर र नाफा रिपोर्ट',
      'billingModuleHelp': 'योजना, बिल र अपग्रेड',
      'teamModuleHelp': 'प्रयोगकर्ता, भूमिका र अनुमति',
      'auditModuleHelp': 'हरेक महत्वपूर्ण काम ट्र्याक गर्नुहोस्',
      'syncModuleHelp': 'अफलाइन र डिभाइस सिंक गतिविधि',
      'supportModuleHelp': 'सहायता टिकट र प्लेटफर्म सन्देश',
      'settingsModuleHelp': 'भाषा, कर, बिल र प्रोफाइल',
      'mobileExpansion':
          'यो सुविधा वेब पोर्टलमा उपलब्ध छ र मोबाइलमा विस्तार गर्न तयार छ।',
      'saved': 'सफलतापूर्वक सेभ भयो।',
      'passwordResetSent': 'पासवर्ड रिसेट अनुरोध पठाइयो।',
      'required': 'आवश्यक विवरण भर्नुहोस्।',
      'dailyOperations': 'दैनिक सञ्चालन',
      'financialsLedgers': 'वित्तीय र खाताहरू',
      'analyticsReminders': 'विश्लेषण र अनुस्मारकहरू',
      'systemAdmin': 'प्रणाली प्रशासन',
    },
  };
}
